version: "3.7"
services:
  svc-keycloak:
    image: hikkoiri/multi-architecture-keycloak:0.0.1
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    depends_on: 
      - postgres
    ports:
      - "8080:8080"

  postgres:
    restart: always     
    image: postgres:alpine
    environment: 
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password